version: '3.8'

services:
  db:
    image: mongo:7.0.14
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=waktaplay

  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./dev/redis/data:/data
      - ./dev/redis/redis.conf:/usr/local/etc/redis/redis.conf
    labels:
      - 'name=redis'
      - 'mode=standalone'
